import enum

class ModelType(enum.StrEnum):
    BASIC = "BASIC"
    POWER = "POWER"
    DOUBLEPOWER = "DOUBLEPOWER"
    TRIPLEPOWER = "TRIPLEPOWER"
    EXPO = "EXPO"
    DOUBLEEXPO = "DOUBLEEXPO"
    TRIPLEEXPO = "TRIPLEEXPO"
    EXPOWER = "EXPOWER"
    DOUBLEEXPOWER = "TRIPLEEXPOWER"
    TRIPLEEXPOWER = "TRIPLEEXPOWER"
    SPLIT = "SPLIT"

Gravity = float